# Generated by Django 4.2.7 on 2026-04-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/')),
                ('site', models.URLField(blank=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa Parceira',
                'verbose_name_plural': 'Empresas Parceiras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('culto', 'Culto'), ('conferencia', 'Conferência'), ('jovens', 'Culto de Jovens'), ('celula', 'Célula'), ('especial', 'Evento Especial'), ('outro', 'Outro')], default='culto', max_length=20)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('local', models.CharField(default='Sede Central', max_length=200)),
                ('recorrente', models.BooleanField(default=False, help_text='Evento que se repete semanalmente')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='FotoCulto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(blank=True, max_length=300)),
                ('imagem', models.ImageField(upload_to='fotos/')),
                ('data_culto', models.DateField()),
                ('destaque', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto de Culto',
                'verbose_name_plural': 'Fotos de Cultos',
                'ordering': ['-data_culto'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.CharField(choices=[('livro', 'Livro'), ('cd', 'CD / DVD'), ('roupa', 'Vestuário'), ('acessorio', 'Acessório'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('disponivel', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
