# Generated by Django 4.2.7 on 2026-04-07 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('local', models.CharField(default='Sede Central', max_length=200, verbose_name='Local')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reuniões',
                'ordering': ['-data', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone (opcional)')),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='gestao.reuniao', verbose_name='Reunião')),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
                'ordering': ['nome'],
                'unique_together': {('reuniao', 'nome')},
            },
        ),
    ]
