# Generated by Django 4.2.7 on 2026-04-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovoMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone / WhatsApp')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('como_conheceu', models.CharField(choices=[('convite', 'Convite de amigo ou familiar'), ('redes_sociais', 'Redes Sociais'), ('youtube', 'YouTube'), ('passando', 'Passando pela rua'), ('outro', 'Outro')], max_length=30, verbose_name='Como nos conheceu?')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações / Pedido de Oração')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendido', models.BooleanField(default=False, verbose_name='Atendido')),
            ],
            options={
                'verbose_name': 'Novo Membro',
                'verbose_name_plural': 'Novos Membros',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='reuniao',
            name='tipo',
            field=models.CharField(choices=[('geral', 'Reunião Geral'), ('obreiros', 'Reunião de Obreiros')], default='geral', max_length=20, verbose_name='Tipo'),
        ),
    ]
