# Generated by Django 4.2.7 on 2026-04-08 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_novomembro_reuniao_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsagracaoOracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Convocação')),
                ('descricao', models.TextField(blank=True, verbose_name='Mensagem de Convocação')),
                ('data_inicio', models.DateTimeField(verbose_name='Início da Consagração')),
                ('data_fim', models.DateTimeField(verbose_name='Fim da Consagração')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa / Visível no Site')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consagração de Oração',
                'verbose_name_plural': 'Consagrações de Oração',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HorarioOracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Obreiro')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone (opcional)')),
                ('hora_inicio', models.DateTimeField(verbose_name='Hora de Início')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consagracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='gestao.consagracaooracao', verbose_name='Consagração')),
            ],
            options={
                'verbose_name': 'Horário de Oração',
                'verbose_name_plural': 'Horários de Oração',
                'ordering': ['hora_inicio'],
                'unique_together': {('consagracao', 'hora_inicio')},
            },
        ),
    ]
